const Map<String, Map<String, dynamic>> mockMovies = {
  "Happy": {
    "title": "Happy Movie",
    "posterUrl": "1",
    "genre": "Comedy",
    "releaseDate": "2023-01-01",
    "rating": 4.5,
    "plotSummary": "happy",
    "cast": ["comedy1", "comedy2", "comedy3"],
    "themeColor": "yellow",
  },
  "Sad": {
    "title": "Sad Movie",
    "posterUrl": "2",
    "genre": "Drama",
    "releaseDate": "2023-02-01",
    "rating": 4.4,
    "plotSummary": "sadly.",
    "cast": ["sad1", "sad2", "sad3"],
    "themeColor": "blue",
  },
  "Exclted": {
    "title": "Exclted movie",
    "posterUrl": "3",
    "genre": "Drama",
    "releaseDate": "2023-03-01",
    "rating": 4.3,
    "plotSummary": "sadly.",
    "cast": ["sad1", "sad2", "sad3"],
    "themeColor": "orange",
  },
  "Relaxed": {
    "title": "Relaxed movie",
    "posterUrl": "4",
    "genre": "Drama",
    "releaseDate": "2023-04-01",
    "rating": 4.2,
    "plotSummary": "Relaxed.",
    "cast": ["R1", "R2", "R3"],
    "themeColor": "green",
  },
  "Angry": {
    "title": "Angry movie",
    "posterUrl": "5",
    "genre": "Drama",
    "releaseDate": "2023-05-01",
    "rating": 4.1,
    "plotSummary": "Angry.",
    "cast": ["A1", "A2", "A3"],
    "themeColor": "red",
  },
};